package fa.training.common;

public enum PageRouterType {
	
	ADD_COMPUTER_PAGE,
	LIST_COMPUTER_PAGE,
	REGISTER_USE_COMPUTER_PAGE,
	ADD_CUSTOMER_PAGE,
	LIST_CUSTOMER_PAGE,
	PROFILE_CUSTOMER_PAGE,
	ADD_SERVICE_PAGE,
	LIST_SERVICE_PAGE,
	USE_SERVICE_PAGE
}
